name: Life-e
favicon: null
layout_spectrum: 0.7030926155857742
typography_spectrum: 0.5640734520275146
title: Life-e
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.47739672171883285
  lightness: 0.44033458177000284
  saturation: 0.15301787806674838
  rhythmicContrast: 0.16836809902451932
purpose: []
